name: Build & upload to Firebase App Distribution 

on: 
  push:
    branches: [ "main", "develop" ]
  pull_request:
    branches: [ "main", "develop" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - uses: actions/setup-node@v3 # This is optional on linux and macOS
      with:
        node-version: 16
    - uses: pocket-apps/action-setup-firebase@v2
      with:
        firebase-token: ${{secrets.FIREBASE_TOKEN}}
    - name: set up JDK 11
      uses: actions/setup-java@v1
      with:
        java-version: 11
    - name: Make gradlew executable
      run: chmod +x ./gradlew

    - name: build debug 
      run: ./gradlew assembleDebug
    - name: upload debug artifact to Firebase App Distribution
      run: firebase appdistribution:distribute app/build/outputs/apk/debug/app-debug.apk --token ${{secrets.FIREBASE_TOKEN}} --app ${{secrets.FIREBASE_APP_ID}} --testers "rosie@medility.ai" --release-notes "Firebase 앱 연동"

    - name: action-slack
      uses: 8398a7/action-slack@v3.8.0
      with:
        status: ${{ job.status }}
        fields: repo,message,commit,author,action,eventName,ref,workflow,job,took
      env:
         SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
